### ISSUE TITLE
Changing Heat Map color Scheme

### ISSUE THREAD

**Issue by Germwise** [TKDBB84/trichomenet#4]
I think it would be very neat if we allowed users to "shift" the heat map color index. Right now our color steps are calibrated towards middle leaves. However some leaves that have less trichomes show all "white" space.

What if in the analysis page we allowed people to shift the index towards more or less sensitive kind of like you allowed me to do by altering the script.

**Comment by TKDBB84** [comment]
Currently the heatmap values and colors are configurable per installation in the settings.ini file.  This could easily be moved into a user interface: however I will need to discuss with the designer how best to incorporate that into the interface.
