### ISSUE TITLE
Autoname leaves

### ISSUE THREAD

**Issue by Germwise** [TKDBB84/trichomenet#6]
Jeff,

Can you make it so that uploaded leaves take on the file name by default?

Users should still have the chance to rename if they want, but to save time, same names would be good.

Also this should be a step towards batch upload. If I have 100 pictuers, it's easier to upload genotypes by batch. I know this will take more time, but keep it in mind for later updates.

**Comment by TKDBB84** [comment]
The name of the file now appears in the text box after you select the file, if you have not entered a name already.  However this has nothing to do with batch uploading.
